version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_med
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Sao_Paulo
      - N8N_HOST=localhost
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
    - ./n8n-data:/home/node/.n8n
    networks:
      - n8n_network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - n8n_network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./med_agenda.db:/metabase-data/med_agenda.db
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n-data: